name: Tests - 2024 - Roc

on: 
  push:
    paths:
      - ".github/workflows/2024-roc.yml"
      - "2024/puzzles/**"
      - "2024/solutions/roc/**"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hasnep/setup-roc@v0.3.0
      with:
        roc-version: nightly
    - name: Run tests
      run: cd ./2024/solutions/roc/ && ./test-all.sh
