name: Run F# tests

on: 
  push:
    paths-ignore:
      - "**.md"
      - ".vscode/**"
      - ".devcontainer/**"
  pull_request:

jobs:
  test-fsharp:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [8.0.201]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Run tests
      run: |
        find . -type d -name "fsharp" -exec find {} -name "test-all.sh" \; | while read testScript
        do
          echo "Running tests in $(dirname "$testScript")"
          (
            cd "$(dirname "$testScript")" || exit
            dotnet tool restore
            ./$(basename "$testScript")
          )
        done
